In [2]:
import numpy as np

def cascade_k(S, v, k) :
    no_blocks = len(S)/k
    if ~(int(no_blocks) == no_blocks) :
        raise ValueError('k does not evenly divide bit string length!')
    return S[((v-1)*k):(v*k)]

def to_basis(chs) :
    basis_map = {0:0, 1:0, 2:1, 3:1}    
    return [basis_map[c] for c in chs]

def to_value(S) :
    key_map = {0:0, 1:1, 2:0, 3:1}
    return [key_map[s] for s in S]

In [3]:
no_tags = 500
alice_tags = np.sort(np.random.randint(0, 100000, no_tags))
alice_chs = np.random.randint(0, 4, no_tags)

bob_tags = alice_tags
bob_chs = alice_chs

bob_chs = np.array(bob_chs)
bob_chs[np.random.randint(0,len(bob_chs), 20)] = 0

alice_bases = to_basis(alice_chs)
bob_bases = to_basis(bob_chs)

alice_values = to_value(alice_chs)
bob_values = to_value(bob_chs)
print(list(alice_chs))
print(list(alice_tags))

print(list(bob_chs))
print(list(bob_tags))
print(len(alice_values))

print(alice_bases)
print(bob_bases)

print(alice_values)
print(bob_values)

[1, 2, 1, 3, 2, 2, 0, 1, 1, 3, 1, 2, 0, 1, 0, 3, 0, 3, 3, 3, 0, 1, 0, 3, 1, 3, 3, 1, 3, 3, 1, 3, 1, 2, 2, 3, 2, 2, 1, 3, 3, 3, 1, 3, 2, 0, 2, 3, 2, 1, 3, 0, 0, 0, 0, 2, 0, 0, 3, 0, 0, 0, 2, 0, 0, 1, 1, 2, 0, 2, 3, 3, 0, 3, 1, 0, 2, 3, 1, 2, 3, 0, 0, 3, 1, 0, 3, 1, 2, 0, 3, 2, 0, 1, 2, 1, 2, 2, 0, 1, 3, 2, 1, 1, 2, 2, 2, 1, 3, 0, 0, 2, 2, 3, 3, 1, 1, 0, 1, 3, 1, 0, 1, 1, 0, 0, 0, 2, 0, 3, 3, 1, 1, 1, 1, 0, 0, 1, 2, 3, 3, 1, 1, 2, 1, 3, 2, 2, 2, 3, 1, 1, 2, 1, 3, 0, 0, 1, 0, 1, 3, 0, 2, 0, 3, 2, 1, 3, 0, 3, 1, 3, 1, 3, 1, 2, 0, 2, 1, 2, 3, 1, 3, 0, 3, 3, 3, 1, 3, 3, 2, 1, 2, 2, 1, 3, 0, 2, 3, 2, 1, 1, 3, 1, 1, 3, 0, 3, 2, 0, 3, 1, 1, 2, 1, 2, 3, 1, 1, 2, 2, 2, 2, 2, 3, 2, 0, 0, 2, 2, 2, 1, 2, 1, 0, 3, 3, 2, 2, 1, 2, 3, 0, 3, 0, 2, 2, 1, 1, 2, 3, 2, 0, 2, 1, 0, 2, 2, 2, 3, 0, 0, 1, 1, 1, 0, 0, 3, 2, 2, 1, 1, 0, 1, 1, 0, 0, 3, 3, 1, 1, 0, 3, 2, 1, 3, 1, 1, 1, 0, 0, 2, 2, 0, 3, 0, 1, 0, 2, 0, 0, 0, 1, 0, 3, 3, 1, 2, 1, 3, 0, 0, 1, 3, 3, 3, 3, 0, 2, 2, 1, 1, 1, 1, 3, 2, 2, 2, 1, 0, 2, 3, 2, 

In [31]:
def do_matching(alice_tags, bob_tags, radius = 1) :
    alice_matched_indices = []
    bob_matched_indices = []
    
    alice_multiple_indices = []
    bob_multiple_indices = []
    
    a_i = 0
    b_i = 0
    
    no_coin = 0
    b_start = 0
    while a_i < len(alice_tags) :
        a = alice_tags[a_i]
        b_i = b_start
        b = bob_tags[b_i]
        while b < (a + radius) and b_i < len(bob_tags):
            b = bob_tags[b_i] 
            if abs(a - b) < radius :
                if a in alice_tags[alice_matched_indices] :
                    alice_multiple_indices.append(a_i)
                    alice_matched_indices.remove(a_i)
                elif b in bob_tags[bob_matched_indices] :
                    bob_multiple_indices.append(b_i)
                    bob_matched_indices.remove(b_i)


                else :    
                    alice_matched_indices.append(a_i)
                    bob_matched_indices.append(b_i)
                    
            b_i += 1
                
        a_i += 1
 
        
        
    return [alice_matched_indices, bob_matched_indices]

[alice_indices, bob_indices] = do_matching(np.array(alice_tags), np.array(bob_tags))
alice_tags = np.array(alice_tags)
bob_tags = np.array(bob_tags)
alice_chs = np.array(alice_chs)
bob_chs = np.array(bob_chs)

print(alice_indices)
print(alice_tags[alice_indices])
print(bob_indices)
print(bob_tags[bob_indices])


alice_matched_chs = alice_chs[alice_indices]
bob_matched_chs = bob_chs[bob_indices]

    

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50, 51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 64, 65, 66, 67, 68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84, 85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98, 99, 100, 101, 102, 103, 104, 105, 106, 107, 108, 109, 110, 111, 112, 113, 114, 115, 116, 117, 118, 119, 120, 121, 122, 123, 124, 125, 126, 127, 128, 129, 130, 131, 132, 133, 134, 135, 136, 137, 138, 139, 140, 141, 142, 143, 144, 145, 146, 147, 148, 149, 150, 151, 152, 153, 154, 155, 156, 157, 158, 159, 160, 161, 162, 163, 164, 165, 166, 167, 168, 169, 170, 171, 172, 173, 174, 175, 176, 177, 178, 179, 180, 181, 182, 183, 184, 185, 186, 187, 188, 189, 190, 191, 192, 193, 194, 195, 196, 197, 198, 199, 200, 201, 202, 203, 204, 205, 206, 207, 208, 209, 210, 211, 212, 213, 214, 215, 216, 217, 218, 219, 220, 221, 222

In [32]:
def do_sifting(alice_matched_chs, bob_matched_chs) :
    alice_bases = to_basis(alice_matched_chs)
    bob_bases = to_basis(bob_matched_chs)
    
    matching_indices = [alice_bases[i] == bob_bases[i] for i in range(len(alice_bases))]
    return [alice_matched_chs[matching_indices], bob_matched_chs[matching_indices]]

[alice_sifted_chs, bob_sifted_chs] = do_sifting(alice_matched_chs, bob_matched_chs)
print(alice_sifted_chs)
print(bob_sifted_chs)

[1 2 1 3 2 2 0 1 1 3 1 2 0 1 0 3 0 3 3 3 0 1 0 3 1 3 3 1 3 3 1 3 1 2 2 3 2
 2 1 3 3 3 1 3 2 0 2 3 2 1 3 0 0 0 0 2 0 0 0 0 0 2 0 1 1 2 0 2 3 3 0 3 1 0
 2 3 1 2 3 0 0 3 1 0 3 1 2 0 2 0 1 2 1 2 2 0 1 3 2 1 1 2 2 2 1 3 0 0 2 2 3
 3 1 1 0 1 3 1 0 1 1 0 0 0 2 0 3 3 1 1 1 1 0 0 1 2 3 1 1 2 1 3 2 2 2 3 1 1
 2 1 3 0 0 1 0 1 3 0 2 0 3 1 3 0 3 1 3 1 3 1 2 0 2 1 2 3 1 3 0 3 3 3 1 3 3
 2 1 2 2 1 3 0 2 3 2 1 1 3 1 1 3 0 3 2 0 3 1 1 2 1 2 3 1 1 2 2 2 2 2 3 2 0
 0 2 2 2 1 2 1 0 3 3 2 2 1 2 3 0 3 0 2 2 1 1 2 2 0 2 1 0 2 2 2 3 0 0 1 1 1
 0 0 3 2 2 1 1 0 1 1 0 0 3 3 1 1 0 3 2 1 3 1 1 1 0 0 2 2 0 3 0 1 0 2 0 0 0
 1 0 3 1 2 1 3 0 0 1 3 3 3 3 0 2 2 1 1 1 1 3 2 2 2 1 0 2 3 2 2 2 3 1 3 1 3
 1 0 0 2 0 2 2 2 2 1 3 1 2 2 3 3 0 2 3 1 3 1 0 0 0 0 1 1 3 2 0 0 2 1 3 3 1
 0 3 1 0 0 2 2 1 2 0 0 3 2 0 1 1 1 2 2 1 2 2 3 0 2 1 1 1 3 1 1 3 0 3 3 0 2
 3 3 2 2 0 1 2 2 3 0 3 0 3 3 2 0 1 2 3 2 3 2 2 0 1 2 1 3 1 1 0 0 0 3 2 0 3
 0 1 1 3 1 3 2 2 1 3 0 2 1 3 0 0 2 2 3 2 2 0 2 0 0 3 0 0 0 3 0 3 1 0 0 1 2
 1 2 0 0 3 0 1]
[1 2 1 3 

In [303]:
alice_key = np.random.choice([0,1,2,3], size = 1000)
print("Alice key:", alice_key[0:50])

q = 0.06
bob_errors = np.random.choice([0,1], size = 1000, p = [1-q, q])
err_ind = np.where(bob_errors)
bob_key = alice_key.copy()
bob_key[err_ind] = np.mod(bob_key[err_ind] + 1, 4)
print("Bob key:  ",  bob_key[0:50])

Alice key: [2 0 2 3 1 1 1 3 2 3 1 0 2 2 2 1 3 1 0 0 3 3 2 1 3 1 3 1 0 1 1 3 0 0 1 2 2
 2 0 0 1 2 0 3 0 3 3 0 2 2]
Bob key:   [2 0 2 3 1 1 1 3 2 3 1 0 2 2 2 1 3 1 0 0 3 3 2 1 3 1 3 1 0 1 1 3 0 0 1 2 2
 2 1 0 1 2 0 3 0 3 3 1 2 2]


In [304]:
def convert_d(A) :
    out = np.array([])
    bin_map = {0:[0,0], 1:[0,1], 2:[1,0], 3:[1,1]}
    for a in A :
        out = np.hstack((out, bin_map[a]))
    return out.astype(int)
print(alice_key[0:50])
print(convert_d(alice_key)[0:50])
print(convert_d(bob_key)[0:50])

[2 0 2 3 1 1 1 3 2 3 1 0 2 2 2 1 3 1 0 0 3 3 2 1 3 1 3 1 0 1 1 3 0 0 1 2 2
 2 0 0 1 2 0 3 0 3 3 0 2 2]
[1 0 0 0 1 0 1 1 0 1 0 1 0 1 1 1 1 0 1 1 0 1 0 0 1 0 1 0 1 0 0 1 1 1 0 1 0
 0 0 0 1 1 1 1 1 0 0 1 1 1]
[1 0 0 0 1 0 1 1 0 1 0 1 0 1 1 1 1 0 1 1 0 1 0 0 1 0 1 0 1 0 0 1 1 1 0 1 0
 0 0 0 1 1 1 1 1 0 0 1 1 1]


In [305]:
# alice_bits = to_value(alice_sifted_chs)
# bob_bits = to_value(bob_sifted_chs)
alice_bits = convert_d(alice_key)
bob_bits = convert_d(bob_key)


leaked_bits = 0
print(alice_bits)
print(bob_bits)

[1 0 0 ... 1 1 1]
[1 0 0 ... 1 1 1]


In [306]:
def cascade_k(S, v, k) :
    no_blocks = len(S)/k
    if not (float(no_blocks).is_integer()) :
        raise ValueError('k does not evenly divide bit string length!')
    return S[((v-1)*k):(v*k)]


def cascade_parity(block) :
    return int(np.sum(block) % 2 == 1)

def cascade_parity_of_all_blocks(S, k) :
    no_blocks = int(len(S)/k)
    return [cascade_parity(cascade_k(S, v, k)) for v in range(1, no_blocks)]

k1 = 100
print(len(alice_bits))
alice_pass_one_parities = cascade_parity_of_all_blocks(alice_bits, k1)
bob_pass_one_parities = cascade_parity_of_all_blocks(bob_bits, k1)



enum_error = enumerate([alice_pass_one_parities[i] != bob_pass_one_parities[i] for i in range(len(alice_pass_one_parities))])
indices_of_errors = [n+1 for (n, v) in enum_error if v ]
print(indices_of_errors)



    


2000
[2, 4, 8, 12, 14, 16, 17]


In [307]:
def cascade_binary(A, B, i) :
    global leaked_bits
    leaked_bits += 1
    if len(A) == 1 :
        return i 
     
    a_first_half_parity = cascade_parity(A[0:int(len(A)/2)])
    b_first_half_parity = cascade_parity(B[0:int(len(B)/2)])
    

    #if len(A) % 2 != 0 : # If A has odd length
    if a_first_half_parity == b_first_half_parity :
        return cascade_binary(A[int(len(A)/2):], B[int(len(A)/2):], i + int(len(A)/2))
    else :
        return cascade_binary(A[0:int(len(A)/2)], B[0:int(len(B)/2)], i)
        
#     if len(A) % 2 == 0 : # If A has even length
#         if a_first_half_parity == b_first_half_parity :
#             return cascade_binary(A[int(len(A)/2):-1], B[int(len(A)/2):-1])
#         else :
#             return cascade_binary(A[0:int(len(A)/2)], B[0:int(len(B)/2)])
    
    
# Do Cascade Pass 1
for j in indices_of_errors :
    alice_block = cascade_k(alice_bits, j, k1)
    bob_block = cascade_k(bob_bits, j, k1)
#     print(alice_block)
#     print(bob_block)
    error_index = cascade_binary(alice_block, bob_block, 0 )
    bob_bits[(j-1)*k1 + error_index] = (bob_bits[(j-1)*k1 + error_index]+1)%2



In [308]:
def cascade_rand_f(k, length) :
    return np.random.choice(list(range(int(np.ceil(length/k)))), size = length)


def cascade_BdelK(B, K) :
    print((np.logical_or(B,K)).astype(int))
    print((np.logical_and(B,K)).astype(int))
    Kprime = np.mod((np.logical_or(B,K) - np.logical_and(B,K)).astype(int))
    return Kprime


def cascade_apply_f(K, f_i, i) :
    return K[ [f == i for f in f_i] ]

#cascade_BdelK([0, 1, 1, 0, 1, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 1, 1, 0, 0], [0, 1, 1, 0, 1, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 1, 1, 0, 1])


def cascade_calc_xj(K, f, j) :
    return np.mod(np.sum(cascade_apply_f(K, f, j)), 2).astype(int)


k = 50
f_i = cascade_rand_f(k, len(alice_bits))
print("f_i: ", f_i)
alice_bits = np.array(alice_bits)
bob_bits = np.array(bob_bits)


# print(cascade_apply_f(alice_bits, f_i, 0) )
# print('aj = ', cascade_calc_xj(alice_bits, f_i, 0) )

ajs = [cascade_calc_xj(alice_bits, f_i, j) for j in range(int(np.ceil(len(alice_bits)/k)))]
print("all aj ", ajs)


# print(cascade_apply_f(bob_bits, f_i, 0))
# print('bj = ', cascade_calc_xj(bob_bits, f_i, 0))

bjs = [cascade_calc_xj(bob_bits, f_i, j) for j in range(int(np.ceil(len(bob_bits)/k)))]
print("all bj: ", bjs, "\n")

print(alice_bits)
print(bob_bits)
print( alice_bits != bob_bits)
print(np.where( alice_bits != bob_bits))

        

f_i:  [13 21 17 ...  8  8 10]
all aj  [0, 0, 1, 1, 1, 0, 1, 1, 0, 0, 1, 0, 0, 1, 0, 0, 1, 0, 0, 1, 0, 0, 1, 0, 0, 1, 0, 0, 1, 0, 1, 0, 0, 0, 0, 1, 0, 0, 1, 1]
all bj:  [1, 0, 1, 0, 1, 1, 0, 1, 1, 0, 0, 0, 0, 0, 0, 1, 0, 1, 1, 0, 1, 0, 1, 1, 0, 1, 1, 0, 0, 1, 1, 0, 1, 1, 0, 1, 1, 0, 1, 0] 

[1 0 0 ... 1 1 1]
[1 0 0 ... 1 1 1]
[False False False ... False False False]
(array([  77,   95,  170,  171,  200,  201,  268,  269,  279,  290,  291,
        297,  354,  355,  364,  365,  414,  415,  438,  439,  529,  556,
        557,  571,  584,  585,  606,  607,  630,  631,  660,  661,  831,
        838,  839,  856,  857,  862,  863,  881,  886,  887,  913,  959,
       1027, 1032, 1033, 1041, 1100, 1101, 1107, 1149, 1256, 1257, 1366,
       1367, 1382, 1383, 1424, 1425, 1556, 1557, 1562, 1563, 1596, 1597,
       1607, 1645, 1670, 1671, 1696, 1697, 1710, 1711, 1729, 1754, 1755,
       1757, 1768, 1769, 1916, 1917, 1920, 1921, 1963, 1980, 1981]),)


In [309]:
print("Starting ######################")
print(np.where(alice_bits != bob_bits))
bad_ind = np.where(alice_bits != bob_bits)

print(alice_bits[bad_ind])
print(bob_bits[bad_ind])
f_i = cascade_rand_f(k, len(alice_bits))

ajs = [cascade_calc_xj(alice_bits, f_i, j) for j in range(int(np.floor(len(alice_bits)/k)))]
print("all aj: ", ajs)

bjs = [cascade_calc_xj(bob_bits, f_i, j) for j in range(int(np.floor(len(bob_bits)/k)))]
print("all bj: ", bjs, "\n")



while(np.any(ajs != bjs)):
    leaked_bits += len(ajs)


    for j in range(len(ajs)) :
        if ajs[j] != bjs[j] :
            f_indices = cascade_apply_f(np.arange(len(alice_bits)), f_i, j)
            error_index_j = cascade_binary(cascade_apply_f(alice_bits, f_i, j), cascade_apply_f(bob_bits, f_i, j), i=0) % len(f_indices)
            print("Bit ", f_indices[error_index_j])# " was ", alice_bits[f_indices[error_index_j]],":",bob_bits[f_indices[error_index_j]], " is now ", (bob_bits[f_indices[error_index]] + 1) % 2  )
#             print(len(bob_bits))
            bob_bits[f_indices[error_index_j]] = (bob_bits[f_indices[error_index_j]] + 1) % 2
    
    print("BEGINNING NEW ROUND ######################")
    print(np.where(alice_bits != bob_bits))
    bad_ind = np.where(alice_bits != bob_bits)
    
    print(alice_bits[bad_ind])
    print(bob_bits[bad_ind])
    f_i = cascade_rand_f(k, len(alice_bits))
    
    ajs = [cascade_calc_xj(alice_bits, f_i, j) for j in range(int(np.floor(len(alice_bits)/k)))]
    print("all aj: ", ajs)

    bjs = [cascade_calc_xj(bob_bits, f_i, j) for j in range(int(np.floor(len(bob_bits)/k)))]
    print("all bj: ", bjs, "\n")
    

print("______________________________________________________")
print("Strings match, ", leaked_bits, " leaked bits")
print(alice_bits)
print(bob_bits)

Starting ######################
(array([  77,   95,  170,  171,  200,  201,  268,  269,  279,  290,  291,
        297,  354,  355,  364,  365,  414,  415,  438,  439,  529,  556,
        557,  571,  584,  585,  606,  607,  630,  631,  660,  661,  831,
        838,  839,  856,  857,  862,  863,  881,  886,  887,  913,  959,
       1027, 1032, 1033, 1041, 1100, 1101, 1107, 1149, 1256, 1257, 1366,
       1367, 1382, 1383, 1424, 1425, 1556, 1557, 1562, 1563, 1596, 1597,
       1607, 1645, 1670, 1671, 1696, 1697, 1710, 1711, 1729, 1754, 1755,
       1757, 1768, 1769, 1916, 1917, 1920, 1921, 1963, 1980, 1981]),)
[0 0 1 1 1 1 0 1 0 1 1 0 0 1 0 1 0 1 0 1 0 1 1 0 0 1 0 1 0 1 1 1 0 1 1 0 1
 0 1 0 1 1 0 0 0 0 1 0 0 1 0 0 1 1 1 1 1 1 1 1 1 1 0 1 0 1 0 0 1 1 0 1 0 1
 0 1 1 0 1 1 0 1 0 1 0 1 1]
[1 1 0 0 0 0 1 0 1 0 0 1 1 0 1 0 1 0 1 0 1 0 0 1 1 0 1 0 1 0 0 0 1 0 0 1 0
 1 0 1 0 0 1 1 1 1 0 1 1 0 1 1 0 0 0 0 0 0 0 0 0 0 1 0 1 0 1 1 0 0 1 0 1 0
 1 0 0 1 0 0 1 0 1 0 1 0 0]
all aj:  [1, 1, 0, 1, 0, 0, 0,